version: '3.4'

services:
  vsoccerdemo:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ./UserSecrets:/root/.microsoft/usersecrets:ro
      - ./ASP.NET/Https:/root/.aspnet/https:ro