name: DEPLOY
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: build docker
      - run: docker-compose up -d
### test