name: DEPLOY
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main
      - run: docker-compose up -d
### test


name: Workshop

on: [push]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2
    - name: Build & run
      run: docker-compose up -d

