name: Workshop

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build & run
      run: docker-compose -f VFootballWorkshop/VFootballWorkshop/docker-compose.yaml up -d

